[build]
  command = "bash ./netlify-build.sh"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "20"
  PROJ_DIR = "/usr"

[build.lifecycle]
  onPreBuild = "apt-get update && apt-get install -y libproj-dev proj-data proj-bin gdal-bin"
