name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy directory
        run: |
          mkdir deploy

          cp -r 127.0.0.1_8081/dl/. deploy/  # core html & site content (if used)
          cp -r NrNzJ3KcpPiT.com deploy/
          cp -r TT9B59GHtmHo.com deploy/
          cp -r TrNlwF50oBkG.com deploy/
          cp -r WMTTk26loLz8.com deploy/
          cp -r bnqOA0GmSrFn.com deploy/
          cp -r psFJ2CW0GE9f.com deploy/
          touch deploy/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
