name: custom deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Current directory: $(pwd)"
          ls -lahR

      - name: Check 
        run: |
          if [ ! -d "127.0.0.1_8081/dl" ]; then
            echo "ERROR: 127.0.0.1_8081/dl directory not found!"
            exit 1
          fi
          echo "Contents of 127.0.0.1_8081/dl:"
          ls -lah 127.0.0.1_8081/dl

      - name: deploy (copy files)
        run: |
          mkdir deploy
          cp -r 127.0.0.1_8081/dl/. deploy/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
