name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files (debug)
        run: ls -lR

      - name: Prepare deploy directory
        run: |
          mkdir deploy
          # Copy your main site files
          cp -r 127.0.0.1_8081/dl/. deploy/
          # Copy all your assets folders from repo root
          cp -r NrNzJ3KcpPiT.com deploy/
          cp -r TT9B59GHtmHo.com deploy/
          cp -r TrNlwF50oBkG.com deploy/
          cp -r WMTTk26loLz8.com deploy/
          cp -r bnqOA0GmSrFn.com deploy/
          cp -r psFJ2CW0GE9f.com deploy/
          # Disable Jekyll so _folders and dotfiles are preserved
          touch deploy/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
